spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: test
    password: test_1111

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379


